language: c

sudo: false

os:
    - linux

cache:
  directories:
    - $TRAVIS_BUILD_DIR/*/
    - $HOME/.elan

install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env

jobs:
  include:
    - stage: Pre-build
      script:
        - (git status | grep  -e "Changes not staged for commit:"); RESULT=$?
        - echo $RESULT
        - if [ $RESULT -eq 0 ]; then git checkout -f HEAD ; fi
        - rm mathlib.txt || true
        - (timeout 120 leanpkg test | grep -e "error"); test $?  -ne 0

    - stage: Test
      script:
        - (git status | grep  -e "Changes not staged for commit:"); test $? -ne 0
        - leanpkg test
        - lean --recursive --export=mathlib.txt
        - leanchecker mathlib.txt

notifications:
  webhooks:
    - https://leanprover.zulipchat.com/api/v1/external/travis?stream=travis&topic=build-status&api_key=SwF1QzwUWol76dCxsYgwHbI6giN3cxGn
