language: c

sudo: false

os:
    - linux

cache:
  directories:
    - $TRAVIS_BUILD_DIR/*/
    - $HOME/.elan

install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env

jobs:
  include:
    - stage: Pre-build
      script:
        - rm mathlib.txt || true
        - find . -name "*.olean" -print
        - timeout 2400 leanpkg test || echo timed out
        # - find . -name "*.lean" -delete
        # - find $HOME/.elan/toolchains/3.4.1/lib/lean/library/ -name "*.lean" -delete

    - stage: Test
      script:
        - find . -name "*.olean" -print
        - leanpkg test
        # - lean tactic/*.lean
        - lean --recursive --export=mathlib.txt
        - leanchecker mathlib.txt
        # - find . -name "*.lean" -delete
        # - find $HOME/.elan/toolchains/3.4.1/lib/lean/library/ -name "*.lean" -delete

notifications:
  webhooks:
    - https://leanprover.zulipchat.com/api/v1/external/travis?stream=travis&topic=build-status&api_key=SwF1QzwUWol76dCxsYgwHbI6giN3cxGn
